BOOKS_BY_CATEGORY = {
    'adventure': ['Harry Potter and the Sorcerer’s Stone', 'The Hobbit', 'Throne of Glass', 'The Grisha Trilogy: Shadow and Bone', 'Stardust', 'Throne of Glass', 'The Grisha Trilogy: Shadow and Bone', 'Stardust', 'A Darker Shade of Magic', 'A Darker Shade of Magic', 'The Ten Thousand Doors of January'],
    'adventure fantasy': ['The Blacktongue Thief'],
    'afro-futurism': ['The Deep'],
    'apocalyptic horror': ['Bird Box', 'The Cabin at the End of the World', 'Bird Box'],
    'arthurian fantasy': ['The Once and Future King'],
    'arthurian legend': ['The Winter King'],
    'body horror': ['The Troop'],
    'caribbean-inspired fantasy': ['Queen of the Conquered'],
    'celtic-inspired fantasy': ['The Harp of Kings'],
    'chinese-inspired': ['Descendant of the Crane'],
    'classic detective mystery': ['The Murder of Roger Ackroyd', 'The Hound of the Baskervilles', 'The ABC Murders'],
    'classic fantasy': ['The Black Cauldron'],
    'classic horror': ['Dracula'],
    'classic mystery': ['The Moonstone'],
    'conspiracy thriller': ['The Da Vinci Code'],
    'cosmic horror': ['The Fisherman', 'The Ballad of Black Tom'],
    'cozy mystery': ["The No. 1 Ladies' Detective Agency", 'Still Life'],
    'crime': ['The Postman Always Rings Twice', 'Silent Night', 'The Lies of Locke Lamora'],
    'crime mystery': ['Sharp Objects', 'The Chestnut Man', 'The Night Fire'],
    'crime thriller': ['The Girl with the Dragon Tattoo', 'The Good Daughter'],
    'dark fairy tale': ['The Hazel Wood'],
    'dark fantasy': ['The Witcher: The Last Wish', 'The Witcher: The Last Wish', 'The Ocean at the End of the Lane', 'The Ocean at the End of the Lane', 'Master of Sorrows', 'The Nevernight Chronicle', 'The Ninth House', 'The Pariah', 'The Magicians', 'The Barrow', 'The Way of Shadows'],
    'dark fantasy/horror': ['The Changeling'],
    'dark magic': ['Wicked Saints', 'Wicked Saints'],
    'dark romance': ['Kingdom of the Wicked'],
    'detective fiction': ['Magpie Murders'],
    'detective mystery': ["The Cuckoo's Calling", 'A Study in Scarlet'],
    'domestic thriller': ['Big Little Lies', 'The Couple Next Door', 'The Family Upstairs'],
    'dragons': ['The Last Namsara'],
    'drama': ['The Lovely Bones'],
    'dystopian': ['An Ember in the Ashes', 'The Bells', 'An Ember in the Ashes'],
    'dystopian fantasy': ['The Bone Season', 'The Bone Season', 'The Bone Season', 'The Fifth Season', 'The Bone Season'],
    'epic fantasy': ['The Priory of the Orange Tree', 'The Name of the Wind', 'The Hobbit', 'A Song of Ice and Fire: A Game of Thrones', 'The Priory of the Orange Tree', 'The Shadow of the Gods', 'The Wheel of Time: The Eye of the World', 'The City of Brass', 'The Inheritance Trilogy: The Hundred Thousand Kingdoms', 'The Black Prism', 'The Shadow of the Gods', 'The Wheel of Time: The Eye of the World', 'The City of Brass', 'The Inheritance Trilogy: The Hundred Thousand Kingdoms', 'The Sword of Shannara', 'The Queens of Innis Lear', 'The Sword of Shannara', 'The Queens of Innis Lear', 'The Priory of the Orange Tree', 'The Lightbringer Series: The Black Prism', 'The Bone Shard Daughter', 'The Ruin of Kings', 'The Shadow Rising', 'The Way of Kings', 'The Priory of the Orange Tree', 'The Dreamblood Duology', 'The Waking Land', 'Furyborn', 'Black Sun', 'The Ninth Rain', 'The Unspoken Name', 'The Shadow of What Was Lost', 'The Priory of the Orange Tree', 'The Jasmine Throne', 'The Bone Shard Daughter', 'The Wolf of Oren-Yaro', 'The Stone Sky', 'The Ruin of Kings', 'The Obelisk Gate', 'The Kingdom of Liars', 'The Priory of the Orange Tree', 'The Black Prism', 'The Grace of Kings', 'The Name of the Wind', 'The Inheritance Trilogy', 'The Queens of Innis Lear', 'Dragon Keeper', "The Emperor's Blades", 'Black Sun', 'The Hundred Thousand Kingdoms', "The Tiger's Daughter", 'The Black Prism', 'Fate of the Fallen', 'The Ruin of Kings'],
    'experimental horror': ['House of Leaves'],
    'experimental/psychological horror': ['House of Leaves'],
    'faerie tale': ['The Iron King', 'The Iron King'],
    'fairy tale retelling': ['Uprooted', 'Uprooted', 'Spinning Silver', 'Spinning Silver'],
    'fairytale retelling': ['Spinning Silver'],
    'fantasy': ['Harry Potter and the Sorcerer’s Stone', 'The Night Circus', 'The Lies of Locke Lamora', 'The Broken Earth: The Fifth Season', 'Uprooted', 'The House in the Cerulean Sea', 'A Court of Thorns and Roses', 'Stardust', 'The Broken Earth: The Fifth Season', 'Uprooted', 'The House in the Cerulean Sea', 'A Court of Thorns and Roses', 'Stardust', 'Spinning Silver', 'The Bear and the Nightingale', 'A Darker Shade of Magic', 'The Paper Menagerie and Other Stories', 'Spinning Silver', 'The Bear and the Nightingale', 'A Darker Shade of Magic', 'The Paper Menagerie and Other Stories', 'The Starless Sea', 'The Winds of Khalakovo', 'The Alloy of Law', 'Daughter of the Moon Goddess', 'The Midnight Library', 'Forest of a Thousand Lanterns', 'A Court of Thorns and Roses', 'Foundryside', 'The House in the Cerulean Sea', 'The Midnight Bargain', 'The Library of the Unwritten', 'The Wandering Inn', 'The Deep', 'The Paper Menagerie and Other Stories', 'The Dreamblood Duology', 'A Wizard’s Guide to Defensive Baking'],
    'fantasy adventure': ['The Blacktongue Thief'],
    'fantasy novella': ['The Emperor’s Soul'],
    'gothic fantasy': ['The Shadow of the Wind'],
    'gothic horror': ['The Haunting of Hill House', 'Frankenstein', 'Mexican Gothic'],
    'gothic mystery': ['The Woman in White', 'The Thirteenth Tale', 'The Shadow of the Wind'],
    'gothic suspense': ['Rebecca'],
    'gothic thriller': ['The Turn of the Key'],
    'grimdark fantasy': ['The Poppy War', 'The Blade Itself', 'The Book of the Ancestor Series', 'The First Law Trilogy', 'We Ride the Storm'],
    'haunted house horror': ['Hell House', 'The Amityville Horror', 'Hell House', 'The Haunting of Ashburn House'],
    'heartwarming': ['The House in the Cerulean Sea'],
    'heist': ['Six of Crows', 'Six of Crows', 'Foundryside'],
    'heist fantasy': ['The Lies of Locke Lamora'],
    'high fantasy': ['The Name of the Wind', 'Mistborn: The Final Empire', 'The Kingkiller Chronicle: The Wise Man’s Fear', 'The Kingkiller Chronicle: The Wise Man’s Fear', 'The Summer Tree', 'The Broken Crown', 'The Firekeeper Saga'],
    'historical adventure': ['The Gilded Wolves', 'The Gilded Wolves'],
    'historical crime thriller': ['The Alienist'],
    'historical fantasy': ['The City of Brass', 'The Ten Thousand Doors of January', 'The Winter of the Witch', 'The Witch Haven', 'The Kingdom of Back', 'The Golem and the Jinni', 'The Winter King', 'The City of Brass', 'A Song for Arbonne', 'Sorcerer to the Crown', 'The Midnight Queen', 'The Golem and the Jinni', 'Throne of Jade'],
    'historical horror': ['The Deep', 'The Hunger'],
    'historical mystery': ['The Name of the Rose', 'The Paris Library'],
    'horror': ['The Changeling'],
    'humor': ['A Wizard’s Guide to Defensive Baking'],
    'japanese mystery': ['The Devotion of Suspect X'],
    'japanese-inspired': ['Shadow of the Fox'],
    'legal thriller': ['The Reversal'],
    'lgbtq+': ['The Priory of the Orange Tree', 'The House in the Cerulean Sea', 'The House in the Cerulean Sea', 'The Priory of the Orange Tree', 'Girls of Paper and Fire', 'Queen of Coin and Whispers'],
    'literary adventure': ['The Library of the Unwritten'],
    'litrpg': ['The Wandering Inn'],
    'magical realism': ['The Ocean at the End of the Lane', 'The Ocean at the End of the Lane', 'The Starless Sea', 'The Inheritance of Orquídea Divina', 'The Night Circus'],
    'middle eastern mythology': ['The City of Brass', 'The City of Brass'],
    'middle eastern-inspired': ['The City of Brass'],
    'middle-grade fantasy': ['A Tale of Magic...'],
    'military fantasy': ['The Rage of Dragons', 'The Poppy War', 'The Rage of Dragons', 'The Poppy War', 'The Rage of Dragons', 'The Poppy War', 'The Rage of Dragons', 'Sword of Kaigen'],
    'mystery': ['The Girl with the Dragon Tattoo', 'Gone Girl', 'The Da Vinci Code', 'The Silent Patient', 'Big Little Lies', 'The Reversal', 'Shutter Island', 'Magpie Murders', 'And Then There Were None', 'The Snowman', 'The Postman Always Rings Twice', 'Bluebird, Bluebird', 'The Secret History', 'The Widow', 'The Turn of the Key', 'The Lovely Bones', 'The Couple Next Door', 'The Wife Between Us', 'One', 'Behind Closed Doors', 'The Good Daughter', 'The Last House on Needless Street', 'I Am Watching You', 'Silent Night', 'The Hunting Party', 'The Family Upstairs', 'We Were Never Here', 'The Guest List', 'The Girl with the Louding Voice', 'The It Girl'],
    'mythological fantasy': ["The Witch's Heart"],
    'mythology': ['Daughter of the Moon Goddess'],
    'nature-inspired fantasy': ['The Waking Land'],
    'nautical fantasy': ['The Bone Ships'],
    'nordic noir': ['The Chestnut Man', 'The Snowman', 'The Chestnut Man'],
    'norse mythology': ['The Shadow of the Gods', 'The Shadow of the Gods'],
    'norse-inspired epic fantasy': ['The Shadow of the Gods'],
    'philosophical fiction': ['The Midnight Library'],
    'police procedural': ['The Night Fire'],
    'political fantasy': ['City of Lies', 'Queen of Coin and Whispers', 'The Goblin Emperor'],
    'political intrigue': ['A Song of Ice and Fire: A Game of Thrones', 'The Cruel Prince', 'The Winds of Khalakovo', 'King of Scars'],
    'psychological crime mystery': ['The Trespasser'],
    'psychological crime thriller': ['In the Woods'],
    'psychological horror': ['The Shining', 'Rosemary’s Baby', 'The Girl Next Door', 'Come Closer', 'A Head Full of Ghosts', 'The Last House on Needless Street'],
    'psychological horror/crime': ['The Silence of the Lambs'],
    'psychological horror/folk horror': ['The Only Good Indians'],
    'psychological horror/thriller': ['Harrow Lake'],
    'psychological mystery': ['Rebecca', 'The Lying Game'],
    'psychological thriller': ['Gone Girl', 'The Silent Patient', 'The Girl on the Train', 'Before I Go to Sleep', 'Shutter Island', 'The Woman in the Window', 'The Secret History', 'The Widow', 'Sharp Objects', 'The Wife Between Us', 'Behind Closed Doors', 'I Am Watching You', 'The Hunting Party', 'We Were Never Here', 'The Guest List', 'Verity', 'The It Girl'],
    'psychological/gothic horror': ['The House Next Door'],
    'psychological/haunted house horror': ['The Grip of It'],
    'psychological/supernatural horror': ['The Devil in Silver', 'The Red Tree', 'The Dead Zone', 'The Between'],
    'psychological/survival horror': ['Penpal'],
    'racial tension': ['Bluebird, Bluebird'],
    'regency-inspired': ['The Midnight Bargain'],
    'retelling': ['The Queens of Innis Lear', 'The Queens of Innis Lear', 'Forest of a Thousand Lanterns', 'The Wrath & the Dawn', 'The Queens of Innis Lear'],
    'romance': ['The Night Circus', 'Caraval', 'A Court of Thorns and Roses', 'Serpent & Dove', 'Caraval', 'A Court of Thorns and Roses', 'Serpent & Dove', 'A Discovery of Witches', 'Crescent City: House of Earth and Blood', 'A Court of Thorns and Roses'],
    'russian folklore': ['The Bear and the Nightingale', 'The Bear and the Nightingale'],
    'sci-fi fantasy': ['To Sleep in a Sea of Stars', 'Heart of Iron'],
    'sci-fi mystery': ['The 7½ Deaths of Evelyn Hardcastle'],
    'science fiction': ['The Broken Earth: The Fifth Season', 'The Broken Earth: The Fifth Season'],
    'short stories': ['The Paper Menagerie and Other Stories', 'The Paper Menagerie and Other Stories', 'The Paper Menagerie and Other Stories'],
    'silkpunk': ['The Grace of Kings'],
    'slasher horror': ['Clown in a Cornfield'],
    'social drama': ['The Girl with the Louding Voice'],
    'southern gothic horror': ['The Elementals', 'Cold Moon Over Babylon'],
    'steampunk fantasy': ['Stormdancer'],
    'superhero': ['Vicious', 'Vicious'],
    'supernatural horror': ['The Exorcist', 'Pet Sematary', 'It', 'Ghost Story', 'Carrie', 'Heart-Shaped Box', 'NOS4A2', 'Slade House'],
    'survival horror': ['The Ruins', 'The Ritual'],
    'suspense': ['And Then There Were None', 'One', 'The Chain', 'Lock Every Door'],
    'thriller': ['The Chestnut Man', 'The Devotion of Suspect X', 'The Chain', 'Lock Every Door'],
    'time loop': ['The 7½ Deaths of Evelyn Hardcastle'],
    'urban fantasy': ['Vicious', 'Vicious', 'A Discovery of Witches', 'Queen of Air and Darkness', 'A Song Below Water', 'Crescent City: House of Earth and Blood', 'The City We Became', 'The Night Watch', 'The War of the Flowers', 'The Broken Kingdoms', 'The Changeling', 'The Rook'],
    'urban fantasy noir': ['The Last Smile in Sunder City'],
    'vampire horror': ['Let the Right One In', "Salem's Lot", 'The Southern Book Club’s Guide to Slaying Vampires'],
    'west african mythology': ['Children of Blood and Bone', 'Children of Blood and Bone'],
    'west african-inspired': ['Children of Blood and Bone'],
    'western adventure': ['The Alloy of Law'],
    'ya': ['Queen of Air and Darkness'],
    'ya fantasy': ['The Gilded Ones', 'The Cruel Prince', 'An Ember in the Ashes', 'Throne of Glass', 'Children of Blood and Bone', 'Caraval', 'The Grisha Trilogy: Shadow and Bone', 'Serpent & Dove', 'Throne of Glass', 'Children of Blood and Bone', 'Caraval', 'The Grisha Trilogy: Shadow and Bone', 'Serpent & Dove', 'The Iron King', 'The Gilded Wolves', 'Six of Crows', 'Wicked Saints', 'The Iron King', 'The Gilded Wolves', 'Six of Crows', 'Wicked Saints', 'The Queen’s Rising', 'Sorcery of Thorns', 'Kingdom of the Wicked', 'Girls of Paper and Fire', 'The Merciful Crow', 'The Hazel Wood', 'The Wrath & the Dawn', 'King of Scars', 'The Bells', 'Fireborne', 'There Will Come a Darkness', 'Descendant of the Crane', 'We Hunt the Flame', 'All the Stars and Teeth', 'Bone Crier’s Moon', 'Shadow of the Fox', 'Children of Blood and Bone', 'The Last Namsara', 'An Ember in the Ashes', 'Blood Heir', 'Ruin and Rising', 'The Iron King', 'Daughter of Smoke and Bone'],
}
